[package]
name = "sb3-burn"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.14.0", features = ["ndarray", "wgpu", "autodiff", "train"], git = "https://github.com/tracel-ai/burn" }
csv = "1.3.0"
indicatif = "0.17.8"
ndarray = "0.15.6"
rand = "0.8.5"
